FROM mongo
#FROM ubuntu:20.04


#ADD TreeMap.TreeData.json /
#ADD TreeMap.TreeDataIndex.json /
#ADD TreeMap.Users.json /
#ADD import.sh /home/


# RUN mongoimport /TreeMap.TreeData.json -d TreeMap -c TreeData --drop
# RUN mongoimport /TreeMap.TreeDataIndex.json -d TreeMap -c TreeDataIndex --drop
#RUN mongoimport /TreeMap.Users.json -d TreeMap -c Users --drop



EXPOSE 27017
